const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "1.0.0",
    title: "Build Api Documentation",
    description:
      "Build Api Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User authentication",
      description: "User signup and login",
    },
    {
      name: "User data",
      description: "User data post, get, update , delete",
    },
    {
      name: "Reset password",
      description: "Reset user password",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",
      name: "X-API-KEY",
      description: "any description",
    },
  },
  definitions: {
    Signup: {
      email: { type: "string", unique: true, required: true },
      password: { type: "string", required: true },
    },
    Login: {
      email: { type: "string", required: true },
      password: { type: "string", required: true },
    },
    User: {
      name: { type: "string", required: true },
      phone: { type: "string", required: true },
      email: { type: "string", required: true },
      image: { type: "string", required: true },
    },
    AddUser: {
      name: { type: "string", required: true },
      phone: { type: "string", required: true },
      email: { type: "string", required: true },
      image: { type: "string", required: true },
    },
  },
};

const outputFile = "./swagger-outputfile.json";
const endpointsFiles = ["./app.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app"); // Your project's root file
});
